### PREREQUISITE: Adapt the URL to the base URL of the deployed service
@hostURL = http://localhost:4004

### Get OData Metadata
GET {{hostURL}}/service/ESPM/$metadata

### Get Purchase Order Data
GET {{hostURL}}/service/ESPM/PurchaseOrderHeaders?$expand=SupplierDetails,Items